### ISSUE TITLE
Provide development environment for smart contract

### ISSUE THREAD

**Issue by jeroenptrs** [be-neo/neoblog#6]
Make sure all parties have the following elements installed:
* http://docs.neo.org/en-us/sc/getting-started-python.html
* https://github.com/CityOfZion/neo-privatenet-docker
* https://github.com/ixje/neon-wallet-db/blob/master/privnet-install.md

**ATTN: BEFORE INSTALLING NEON-WALLET-DB!**
The last bullet point will attach neon-wallet-db to privatenet docker, when restarting your docker when `neon-wallet-db` is installed, use the following command instead to expose port 5000 as well:
`docker run -d --name neo-privnet-rpc -p 20333-20336:20333-20336/tcp -p 30333-30336:30333-30336 -p 5000:5000 -h neo-privnet-rpc neo-privnet-rpc`
Or 
`docker run -d --name neo-privnet-with-gas -p 20333-20336:20333-20336/tcp -p 30333-30336:30333-30336/tcp -p 5000:5000 -h metachris/neo-privnet-with-gas metachris/neo-privnet-with-gas` 
when using the privnet-with-gas from metachris

**Comment by jeroenptrs** [comment]
🙌 my docker environment has been reset 🙌

**Comment by DalderupMaurice** [comment]
🙌 my docker environment has been reset 🙌
